spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          open-in-view: false
          use_sql_comments: true
          type:
            resolver: org.hibernate.type.BasicTypeResolverStandardImpl
          dialect: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 877903331004-vd5gr1otqh7ekjrjqkietgcl9adhdm7c.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

mvc:
  path-match:
    matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp-time: ${JWT_ACCESS_EXP_TIME}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE